language: python
python:
  - 2.7
  - 3.5
  - 3.6

cache: pip

install:
  - pip install -e .
  - pip install tensorflow==1.12.0
  - pip install coverage
  - pip install jupyter
  - pip install matplotlib
  - pip install scipy

script:
  - pytest tests/
